---
title: "cph_738_h5"
author: "grienne"
date: "October 4, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Foundation}

library(dplyr)
library(ggplot2)
library(readxl)
library(lme4)

dat <- read_excel("EX854_V3_DH_2.xlsx")

```



```{r Code Transfer}
## handling date observations 
## Date of first StUD Dx
dat$StUD_XDt <- as.Date(dat$StUD_XDt)
## Date of first remission
dat$remis_dt <- as.Date(dat$remis_dt)
## Time to remission (in days)
dat$Days.to.remission <- with(dat,
                              difftime(remis_dt, StUD_XDt, units = "days")
                              )
## make it a numeric variable
dat$Days.to.remission <- as.numeric(dat$Days.to.remission)
summary(dat$Days.to.remission)

## create a flag for bupropion prescription
dat$BupFlag <- with(dat,
                    ifelse(Bupropion == 0, 0, 1)
                    )
## relable SEX
dat$gender <- as.factor(with(dat, 
                            ifelse(SEX == 1, 'Male', 'Female')
                            )
                        )
## relationship with employee
dat$emp <- as.factor(with(dat,
                          ifelse(EMPREL == 1, "Employee",
                          ifelse(EMPREL == 2, "Spouse",
                          ifelse(EMPREL == 3, "Child",
                                 "Dependent")))))
## StUD type
dat$SUD_Type <- with(dat,
                      ifelse(StUD_Type == 1, "Cocaine",
                             ifelse(StUD_Type == 2, "Amphetamine",
                                    "Both")
                             )
                     )

## State indicator 
dat$State <- with(dat,
                  ifelse(EGEOLOC == 41, 'alabama',
                  ifelse(EGEOLOC == 52, 'arizona',
                  ifelse(EGEOLOC == 46, 'arkansas',
                  ifelse(EGEOLOC == 62, 'california',
                  ifelse(EGEOLOC == 53, 'colorado',
                  ifelse(EGEOLOC == 4,  'connecticut',
                  ifelse(EGEOLOC == 32, 'delaware',
                  ifelse(EGEOLOC == 31, 'district of columbia',
                  ifelse(EGEOLOC == 33, 'florida',
                  ifelse(EGEOLOC == 34, 'georgia',
                  ifelse(EGEOLOC == 54, 'idaho',
                  ifelse(EGEOLOC == 16, 'illinois',
                  ifelse(EGEOLOC == 17, 'indiana',
                  ifelse(EGEOLOC == 22, 'iowa',
                  ifelse(EGEOLOC == 23, 'kansas',
                  ifelse(EGEOLOC == 42, 'kentucky',
                  ifelse(EGEOLOC == 47, 'louisiana',
                  ifelse(EGEOLOC ==  5, 'maine',
                  ifelse(EGEOLOC == 35, 'maryland',
                  ifelse(EGEOLOC ==  6, 'massachusetts',
                  ifelse(EGEOLOC == 18, 'michigan',
                  ifelse(EGEOLOC == 24, 'minnesota',
                  ifelse(EGEOLOC == 43, 'mississippi',
                  ifelse(EGEOLOC == 25, 'missouri',
                  ifelse(EGEOLOC == 55, 'montana',
                  ifelse(EGEOLOC == 26, 'nebraska',
                  ifelse(EGEOLOC == 56, 'nevada',
                  ifelse(EGEOLOC ==  7, 'new hampshire',
                  ifelse(EGEOLOC == 11, 'new jersey',
                  ifelse(EGEOLOC == 57, 'new mexico',
                  ifelse(EGEOLOC == 12, 'new york',
                  ifelse(EGEOLOC == 36, 'north carolina',
                  ifelse(EGEOLOC == 27, 'north dakota',
                  ifelse(EGEOLOC == 19, 'ohio',
                  ifelse(EGEOLOC == 48, 'oklahoma',
                  ifelse(EGEOLOC == 64, 'oregon',
                  ifelse(EGEOLOC == 13, 'pennsylvania',
                  ifelse(EGEOLOC ==  8, 'rhode island',
                  ifelse(EGEOLOC == 37, 'south carolina',
                  ifelse(EGEOLOC == 28, 'south dakota',
                  ifelse(EGEOLOC == 44, 'tennessee',
                  ifelse(EGEOLOC == 49, 'texas',
                  ifelse(EGEOLOC == 58, 'utah',
                  ifelse(EGEOLOC ==  9, 'vermont',
                  ifelse(EGEOLOC == 38, 'virginia',
                  ifelse(EGEOLOC == 65, 'washington',
                  ifelse(EGEOLOC == 39, 'west virginia',
                  ifelse(EGEOLOC == 20, 'wisconsin',
                  ifelse(EGEOLOC == 59, 'wyoming',
                         NA))))))))))))))))))))))))))))))))))))))))))))))))))

## log-transform days to remission
dat$log.days <- log(dat$Days.to.remission)


```


```{r Question 1}

fit_q1 <- lm(log.days ~ State - 1, data = dat)
summary(fit_q1)

#parameter estimate
q1.beta <- coefficients(fit_q1)
q1.beta

#Std Errors
q1.err <- coefficients(summary(fit_q1))[,2]
q1.err

#confidence intervals, didnt need, used the geom_errorbar function instead
##ci_q1 <- confint(fit_q1)

#state sample size
state_sample_size <- aggregate(log.days ~ State, data = dat, FUN = length)


#Created Data Frame of Needed Items
q1_data <- data.frame(state_sample_size ,q1.beta, q1.err)
names(q1_data) <- c("State", "State_Sample_Size", "Mean_Estimate", "Standard_Error")


fit.lm <- lm(log.days ~ State - 1, data = dat)
summary(fit.lm)
State <- sub("State", "", names(coef(fit.lm)))


## plot
p <- ggplot(aes(x = q1_data$State_Sample_Size, y = q1_data$Mean_Estimate), data = q1_data)
p + geom_point()+
      geom_errorbar(ymin = q1_data$Mean_Estimate - q1_data$Standard_Error, ymax = q1_data$Mean_Estimate + q1_data$Standard_Error) +
      geom_hline(yintercept = I(mean(q1_data$Mean_Estimate, na.rm = T)))

```





```{r Question 2}


q2_mlm <- lmer(log.days ~ BupFlag + (1|State), data = dat)
summary(q2_mlm)

#parameters
q2.beta <- coefficients(q2_mlm)
q2.beta


#state sample size
state_sample_size <- aggregate(log.days ~ State, data = dat, FUN = length)


q2_fixef <- fixef(q2_mlm, condVar = TRUE)
q2_fixef_dat <- q2_fixef %>% data.frame()


rr <- ranef(q2_mlm, condVar = TRUE) 
mlm.dat <- rr %>% data.frame


#Created Data Frame of Needed Items
q2_data <- data.frame(state_sample_size ,q1.beta, mlm.dat$condsd)
names(q2_data) <- c("State", "State_Sample_Size", "Mean_Estimate", "Standard_Error")


p <- ggplot(aes(x = q2_data$State_Sample_Size, y = q2_data$Mean_Estimate), data = q2_data)
p + geom_point()+
      geom_errorbar(ymin = q2_data$Mean_Estimate - q2_data$Standard_Error, ymax = q2_data$Mean_Estimate + q2_data$Standard_Error) +
      geom_hline(yintercept = I(mean(q2_data$Mean_Estimate, na.rm = T)))


```